
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Internal Server Error
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.322+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_AmendacallbackURI_500", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTAmendacallbackURI500 extends Exception {

    private com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI500;

    public PUTAmendacallbackURI500() {
        super();
    }

    public PUTAmendacallbackURI500(String message) {
        super(message);
    }

    public PUTAmendacallbackURI500(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTAmendacallbackURI500(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI500) {
        super(message);
        this.putAmendacallbackURI500 = putAmendacallbackURI500;
    }

    public PUTAmendacallbackURI500(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI500, java.lang.Throwable cause) {
        super(message, cause);
        this.putAmendacallbackURI500 = putAmendacallbackURI500;
    }

    public com.laegler.openbanking.soap.model.OBErrorResponse1 getFaultInfo() {
        return this.putAmendacallbackURI500;
    }
}
