
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Bad request
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.323+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_AmendacallbackURI_400", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTAmendacallbackURI400 extends Exception {

    private com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI400;

    public PUTAmendacallbackURI400() {
        super();
    }

    public PUTAmendacallbackURI400(String message) {
        super(message);
    }

    public PUTAmendacallbackURI400(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTAmendacallbackURI400(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI400) {
        super(message);
        this.putAmendacallbackURI400 = putAmendacallbackURI400;
    }

    public PUTAmendacallbackURI400(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putAmendacallbackURI400, java.lang.Throwable cause) {
        super(message, cause);
        this.putAmendacallbackURI400 = putAmendacallbackURI400;
    }

    public com.laegler.openbanking.soap.model.OBErrorResponse1 getFaultInfo() {
        return this.putAmendacallbackURI400;
    }
}
