
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Forbidden
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:26.939+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_UpdateaclientbywayofClientID_403", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTUpdateaclientbywayofClientID403 extends Exception {

    private com.laegler.openbanking.soap.model.OBErrorResponse1 putUpdateaclientbywayofClientID403;

    public PUTUpdateaclientbywayofClientID403() {
        super();
    }

    public PUTUpdateaclientbywayofClientID403(String message) {
        super(message);
    }

    public PUTUpdateaclientbywayofClientID403(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTUpdateaclientbywayofClientID403(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putUpdateaclientbywayofClientID403) {
        super(message);
        this.putUpdateaclientbywayofClientID403 = putUpdateaclientbywayofClientID403;
    }

    public PUTUpdateaclientbywayofClientID403(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 putUpdateaclientbywayofClientID403, java.lang.Throwable cause) {
        super(message, cause);
        this.putUpdateaclientbywayofClientID403 = putUpdateaclientbywayofClientID403;
    }

    public com.laegler.openbanking.soap.model.OBErrorResponse1 getFaultInfo() {
        return this.putUpdateaclientbywayofClientID403;
    }
}
