-------------------------------------------------------------------------------
Test set: com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest
test_personalCurrentAccountsGet_200  Time elapsed: 0 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_200(PersonalCurrentAccountsApiIntegrationTest.java:56)

test_personalCurrentAccountsGet_400  Time elapsed: 0.001 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_400(PersonalCurrentAccountsApiIntegrationTest.java:38)

test_personalCurrentAccountsGet_408  Time elapsed: 0 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_408(PersonalCurrentAccountsApiIntegrationTest.java:62)

test_personalCurrentAccountsGet_429  Time elapsed: 0.002 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_429(PersonalCurrentAccountsApiIntegrationTest.java:68)

test_personalCurrentAccountsGet_500  Time elapsed: 0.003 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_500(PersonalCurrentAccountsApiIntegrationTest.java:44)

test_personalCurrentAccountsGet_503  Time elapsed: 0.002 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at com.laegler.openbanking.api.integration.PersonalCurrentAccountsApiIntegrationTest.test_personalCurrentAccountsGet_503(PersonalCurrentAccountsApiIntegrationTest.java:50)

